version: '3'

services:
  myapp1:
    image: myapp
    ports:
    - 8081:8080
  myapp2:
    image: myapp
    ports:
    - 8082:8080
  myapp3:
    image: myapp
    ports:
    - 8083:8080
  nginx:
    image: nginx:1.17.2-alpine
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - myapp1
    - myapp2
    - myapp3
